apiVersion: batch/v1
kind: CronJob
metadata:
  name: gitops-prod-operator
  namespace: prod
spec:
  schedule: "*/2 * * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      backoffLimit: 0
      template:
        spec:
          restartPolicy: Never
          serviceAccountName: gitops
          containers:
            - name: gitops-operator
              image: sandervanvugt/gittools
              command: [sh, -e, -c]
              args:
                - git clone https://github.com/sandervanvugt/gitops-preprod /tmp/gitops-preprod &&\ 
                  find /tmp/gitops-preprod -name '*.yaml' -exec kubectl apply -f {} \;
